name: Build NixOS modules

on:
  push:
    branches: [main]
    paths:
    - "nixos/**"
    - "flake.*"

  pull_request:
    branches: [main]
    paths:
    - "nixos/**"
    - "flake.*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Nix
      uses: cachix/install-nix-action@v18

    - name: Build modules
      shell: bash
      run: |
        modules=($(nix eval .#nixosModules --apply 'x: builtins.toString (builtins.attrNames x)' | tr -d \"))
        for module in "${modules[@]}"; do
          CI_MODULE="$module" nix build --impure .#nixosConfigurations.ci.config.system.build.toplevel
        done
