name: Update flake.lock

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * SAT"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v18

      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@v15
        with:
          token: ${{ secrets.GH_TOKEN_FLAKE_LOCK_UPDATES }}
          commit-msg: "chore(flake.lock): update inputs"
          pr-title: "Update flake inputs"
          pr-labels: |
            automated
